---
title: "R Notebook"
output: html_notebook

---
<style type="text/css">

body, td {
   font-size: 12px;
}
code.r{
  font-size: 12px;
}
pre {
  font-size: 12px
}
</style>

```{r set up ,include=FALSE}
library(knitr)
knitr::opts_chunk$set(cache = T, warning = F,
                      message = F, echo = T, dpi = 180,
                      fig.width = 8, fig.height = 5)

theme_set(theme_bw() +
         theme(plot.title = element_text(size = 15, face = "bold"),
               plot.subtitle = element_text(size = 12, face = "bold"),
               axis.text.x = element_text(size = 8),
               axis.text.y = element_text(size = 8),
               axis.title.x = element_text(size = 12),
               axis.title.y = element_text(size = 12),
               legend.text =element_text(size = 12),
               legend.title =element_text(size = 12)
              )
          )

# tidymodels
for (package in c('janitor','skimr', 'correlationfunnel', 'DataExplorer')) {
  if (!require(package, character.only=T, quietly=T)) {
    install.packages(package)
    library(package, character.only=T)
  }
}

# tidymodels
for (package in c('gghighlight', 'patchwork', 'ggplot2', 'GGally', 'highcharter','correlationfunnel','plotly')) {
  if (!require(package, character.only=T, quietly=T)) {
    install.packages(package)
    library(package, character.only=T)
  }
}

# Core
for (package in c('doParallel', 'tidyverse', 'tidyquant', 'knitr', "tidymodels")) {
  if (!require(package, character.only=T, quietly=T)) {
    install.packages(package)
    library(package, character.only=T)
  }
}
all_cores <- parallel::detectCores(logical = FALSE)
registerDoParallel(cores = all_cores)
```


```{r}

hotels <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-11/hotels.csv") %>%
  clean_names()
  # select(순서,everthing())

cocktails_parsed <- boston_cocktails %>%
  mutate(
    ingredient = str_to_lower(ingredient),
    ingredient = str_replace_all(ingredient, "-", " "),
    ingredient = str_remove(ingredient, " liqueur$"),
    ingredient = str_remove(ingredient, " (if desired)$"),
    ingredient = case_when(
      str_detect(ingredient, "bitters") ~ "bitters",
      str_detect(ingredient, "lemon") ~ "lemon juice",
      str_detect(ingredient, "lime") ~ "lime juice",
      str_detect(ingredient, "grapefruit") ~ "grapefruit juice",
      str_detect(ingredient, "orange") ~ "orange juice",
      TRUE ~ ingredient
    ),
    measure = case_when(
      str_detect(ingredient, "bitters") ~ str_replace(measure, "oz$", "dash"),
      TRUE ~ measure
    ),
    measure = str_replace(measure, " ?1/2", ".5"),
    measure = str_replace(measure, " ?3/4", ".75"),
    measure = str_replace(measure, " ?1/4", ".25"),
    measure_number = parse_number(measure),
    measure_number = if_else(str_detect(measure, "dash$"),
      measure_number / 50,
      measure_number
    )
  ) %>%
  add_count(ingredient) %>%
  filter(n > 15) %>%
  select(-n) %>%
  distinct(row_id, ingredient, .keep_all = TRUE) %>%
  na.omit()

cocktails_parsed
# kable(head(hotel_stays), caption = "table with kable") #깔끔한 테이블 표현 (양 적을때)
```

```{r}
cocktails_df <- cocktails_parsed %>%
  select(-ingredient_number, -row_id, -measure) %>%
  tidyr::pivot_wider(names_from = ingredient, values_from = measure_number) %>%
  janitor::clean_names()

cocktails_df[is.na(cocktails_df)] <- 0

cocktails_df
```

```{r}
library(tidymodels)

pca_rec <- recipe(~., data = cocktails_df) %>%
  update_role(name, category, new_role = "id") %>%
  step_normalize(all_predictors()) %>%
  step_pca(all_predictors())

pca_prep <- prep(pca_rec)

pca_prep
```

```{r}
tidied_pca <- tidy(pca_prep, 2)

tidied_pca %>%
  filter(component %in% paste0("PC", 1:5)) %>%
  mutate(component = fct_inorder(component)) %>%
  ggplot(aes(value, terms, fill = terms)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~component, nrow = 1) +
  labs(y = NULL)

```

```{r}
library(tidytext)
tidied_pca %>%
  filter(component %in% paste0("PC", 1:4)) %>%
  group_by(component) %>%
  top_n(8, abs(value)) %>%
  ungroup() %>%
  mutate(terms = reorder_within(terms, abs(value), component)) %>%
  ggplot(aes(abs(value), terms, fill = value > 0)) +
  geom_col() +
  facet_wrap(~component, scales = "free_y") +
  scale_y_reordered() +
  labs(
    x = "Absolute value of contribution",
    y = NULL, fill = "Positive?"
  )
```

```{r}
juice(pca_prep) %>%
  ggplot(aes(PC1, PC2, label = name)) +
  geom_point(aes(color = category), alpha = 0.7, size = 2) +
  geom_text(check_overlap = TRUE, hjust = "inward") +
  labs(color = NULL)
```


## UMAP

```{r }
library(embed)
umap_rec <- recipe(~., data = cocktails_df) %>%
  update_role(name, category, new_role = "id") %>%
  step_normalize(all_predictors()) %>%
  step_umap(all_predictors())

umap_prep <- prep(umap_rec)

umap_prep
```


## 막대 그래프
```{r}

juice(umap_prep) %>%
  ggplot(aes(umap_1, umap_2, label = name)) +
  geom_point(aes(color = category), alpha = 0.7, size = 2) +
  geom_text(check_overlap = TRUE, hjust = "inward") +
  labs(color = NULL)

```

```{r}
hotel_stays %>%
  mutate(arrival_date_month = factor(arrival_date_month,
    levels = month.name
  )) %>%
  count(hotel, arrival_date_month, children) %>%
  group_by(hotel, children) %>%
  mutate(proportion = n / sum(n)) %>%
  plot_ly(x = ~arrival_date_month , y = ~proportion, color = ~children, type = "bar") %>%
  layout(title = "Occupation Type Group",
         barmode = 'group',
         xaxis = list(title = ""),
         yaxis = list(title = ""))

```

```{r}
trace_0 <- rnorm(100, mean = 5)
trace_1 <- rnorm(100, mean = 0)
trace_2 <- rnorm(100, mean = -5)
x <- c(1:100)

data <- data.frame(x, trace_0, trace_1, trace_2)

fig <- plot_ly(data, x = ~x, y = ~trace_0, name = 'trace 0', type = 'scatter', mode = 'lines') 
fig <- fig %>% add_trace(y = ~trace_1, name = 'trace 1', mode = 'lines+markers') 
fig <- fig %>% add_trace(y = ~trace_2, name = 'trace 2', mode = 'markers')

fig
```

## 데이터 한판에 보기
```{r}
hotel_stays %>%
  select(
    children, adr,
    required_car_parking_spaces,
    total_of_special_requests
  ) %>%
  ggpairs(mapping = aes(color = children))
```

# 산점도 그래프
```{r}
hotel_stays %>%
    ggplot(aes(lead_time, adr)) +
    geom_point(color = palette_light()["blue"], alpha = 0.15) +
    geom_smooth(method = "lm") +
    scale_y_log10(label = scales::dollar_format()) +
    theme_tq() 
    # labs(title = "Engine Horsepower vs MSRP by Vehicle Age",
    #      x = "Engine HP", y = "MSRP (log scale)")
```

## 하이라이트 적용
```{r}
hotel_stays %>%
    ggplot(aes(lead_time, adr)) +
    geom_point(color = palette_light()["blue"], alpha = 0.15) +
    geom_smooth(method = "lm") +
    scale_y_log10(label = scales::dollar_format()) +
    gghighlight(lead_time > 600, label_key = lead_time, 
                unhighlighted_colour = alpha("grey", 0.05),
                label_params = list(size = 2.5)) +

    theme_tq() 
    # labs(title = "Engine Horsepower vs MSRP by Vehicle Age",
    #      x = "Engine HP", y = "MSRP (log scale)")
```

```{r}
# select_if(is.numeric) 숫자형만

hotel_stays %>% select(-reservation_status_date) %>% binarize(n_bins = 5, thresh_infreq = 0.01 , name_infreq = "OUTHER", one_hot = T) %>%
    correlate(lead_time__5_27) %>%
    plot_correlation_funnel()


```


```{r}
hotel_stays %>% ggpairs(columns=c(2,7,26), aes(colour=children, alpha=0.4),
                 lower=list(continuous=wrap("smooth", method="loess", se=F)))
```